### PR TITLE
Better heuristic to distinguish sorts from terms 

### LINKED ISSUE #43: Better heuristic to guess declare-const vs assert
Right now unused variables are treated as assertions, e.g., this fails:

```
_ : (x y : ℤ) → x ≤ x  -- Unrecognized identifier Agda.Builtin.Int.Int in script "(assert Agda.Builtin.Int.Int)"
```

Maybe a better heuristic is to try decoding every element both as a sort and as a term and pick whichever succeeds. It would also be useful to just drop uninterpretable assumptions, so that you can use `solveZ3` deep in a term with a lot of junk in the context.

It doesn't seem straightforward to do this at the moment because of the current architecture that produces a `RawScript` at a stage where the theory-specific decoding functions aren't available.

### PR DESCRIPTION
**Pull request by Lysxia**
Closes #43

- Try encoding an Agda type as either a sort or term and pick the one that succeeds.
- Also ignore assumptions that cannot be encoded in SMT-LIB.
- Merge the functionality of the modules `SMT.Theory.Raw.Reflection`
  and `SMT.Script.Reflection`, deleting the former. I moved the comments from there too.
- Improve error messages when the encoding fails, and also
  report ignored assumptions if the solver rejects an assertion.

### CODE REVIEW

**Comment by Lysxia** [comment]
I see setup-agda uses git tags to identify library versions. Should I target agda-stdlib-1.7 instead?

**Comment by wenkokke** [comment]
Yes, ideally, schmitty should depend on the latest stable release. 

Though it's probably worthwhile to keep the changes around for when the next version of the standard library is released.

**Comment by wenkokke** [comment]
I see that the tests are broken due to a bug on my side of things (<https://github.com/wenkokke/setup-agda/issues/136>). I'll push a fix for this to setup-agda!

**Comment by wenkokke** [comment]
Fixed setup-agda and it looks like the tests are all passing! :)

**Pull request merged**
